// <auto-generated />
using System;
using LifeTag.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeTag.Infrastructure.Migrations
{
    [DbContext(typeof(LifeTagDbContext))]
    partial class LifeTagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeTag.Core.Entities.ProfileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSectionId");

                    b.ToTable("ProfileEntries");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.ProfileSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ProfileSections");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = new Guid("b1e84d41-35b8-4c3e-9088-2c26f04f29a0"),
                            IsActive = false,
                            IsPinProtected = true,
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("c3a881e1-e17f-4422-901d-5baab2c792f9"),
                            IsActive = false,
                            IsPinProtected = true,
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("a9c14bc6-8d69-450f-90db-cd0811eef2a8"),
                            IsActive = false,
                            IsPinProtected = true,
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Guid = new Guid("ff9c0179-11ba-447f-859a-f4327ea6eeb4"),
                            IsActive = false,
                            IsPinProtected = true,
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Guid = new Guid("d2e5a781-bc5a-474c-83b0-6ef184a4f826"),
                            IsActive = false,
                            IsPinProtected = true,
                            Pin = "1234"
                        });
                });

            modelBuilder.Entity("LifeTag.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.ProfileEntry", b =>
                {
                    b.HasOne("LifeTag.Core.Entities.ProfileSection", "ProfileSection")
                        .WithMany("Entries")
                        .HasForeignKey("ProfileSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileSection");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.ProfileSection", b =>
                {
                    b.HasOne("LifeTag.Core.Entities.UserProfile", "UserProfile")
                        .WithMany("Sections")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.Tag", b =>
                {
                    b.HasOne("LifeTag.Core.Entities.User", "User")
                        .WithOne("ActiveTag")
                        .HasForeignKey("LifeTag.Core.Entities.Tag", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.UserProfile", b =>
                {
                    b.HasOne("LifeTag.Core.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LifeTag.Core.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.ProfileSection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.User", b =>
                {
                    b.Navigation("ActiveTag");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeTag.Core.Entities.UserProfile", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
